### ISSUE TITLE
Error loading the serialized model in C++

### ISSUE THREAD

**Issue by hagerrady13** [tobiascz/MNIST_Pytorch_python_and_capi#2]
**Error:**
terminate called after throwing an instance of 'c10::Error'
  what():  read_bytes == 8 ASSERT FAILED at /pytorch/caffe2/serialize/inline_container.h:182, please report a bug to PyTorch. Expected to read 8 bytes but got %llu bytes0 (read64BitIntegerLittleEndian at /pytorch/caffe2/serialize/inline_container.h:182)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7fdb8b4aacd1 in xxx/libtorch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7fdb8b4aa59a in xxx/libtorch/lib/libc10.so)
frame #2: <unknown function> + 0x58df5b (0x7fdb94359f5b in /xxx/libtorch/lib/libtorch.so.1)
frame #3: <unknown function> + 0x58ecc5 (0x7fdb9435acc5 in /xxx/libtorch/lib/libtorch.so.1)
frame #4: <unknown function> + 0x58f0e3 (0x7fdb9435b0e3 in /xxx/libtorch/lib/libtorch.so.1)
frame #5: <unknown function> + 0x58c41d (0x7fdb9435841d in /xxx/libtorch/lib/libtorch.so.1)
frame #6: torch::jit::load(std::istream&) + 0xb4 (0x7fdb943595d4 in /xxx/libtorch/lib/libtorch.so.1)
frame #7: torch::jit::load(std::string const&) + 0x27 (0x7fdb943596a7 in /xxx/libtorch/lib/libtorch.so.1)
frame #8: main + 0x63 (0x424156 in ./cpp_mnist)
frame #9: __libc_start_main + 0xf0 (0x7fdb8ab5c830 in /lib/x86_64-linux-gnu/libc.so.6)
frame #10: _start + 0x29 (0x4239a9 in ./cpp_mnist)

Aborted (core dumped)

**Comment by tobiascz** [comment]
Could you check in which line this happens? 
Check if the frame you put into the —> forward is actually empty

**Comment by hagerrady13** [comment]
I ran the code as it is. This error happens in line 28 
``` std::shared_ptr<torch::jit::script::Module> module = torch::jit::load("../model_trace.pt"); ```

Which pytorch version are you using? I am using "1.0.0.dev20181029".

**Comment by tobiascz** [comment]
Sorry I can’t check right now but I am probably using an older version than you are using. Try to train your own model with the included python script! And use your own model in c++. This should work since you use the same version for training and running!

**Comment by hagerrady13** [comment]
@tobiascz I have already tried saving and loading my own model but the same error is there. I still have no idea what the problem can be.

**Comment by tobiascz** [comment]
Maybe you are using a different pytorch version in python when you try to train/save/trace the model and in C++?

**Comment by hagerrady13** [comment]
I did try that. I am still getting the same error. Can you please tell which version are you currently using?

**Comment by hagerrady13** [comment]
@tobiascz any updates from your side?

**Comment by tobiascz** [comment]
@hagerrady13 thanks for reminding! My Version is 1.0.0.dev20181003. So its slightly older than your version. I will try to update to the newest version and check if it still runs for me next week.

**Comment by hagerrady13** [comment]
@tobiascz it works fine after upgrading both Pytorch python API and libtorch to version 1.0.0.dev20181121. Thanks!
